services:
  web:
    image: nginx:alpine
    ports:
      - "9091:80"
    volumes:
      - ./html:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./html:/var/www/html